
version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:12.22.9

    working_directory: ~/repo

    # Add steps to the job
    steps:
      - checkout
      - run: npm install
      - run: npm test

